# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.define "master" do |subconfig|
        subconfig.vm.box = "generic/ubuntu2004"
        subconfig.vm.hostname = "master"
        subconfig.vm.provider "virtualbox" do |vb|
	        vb.memory = "512"  
	    end

        subconfig.vm.provision "ansible" do |a|
            a.verbose = "v"
            a.playbook = "master_playbook.yaml"
        end
    end
end