version: '3'
services:
  nextcloud:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - nextcloud-data:/var/www/html/nextcloud
      - ./nextcloud.conf:/etc/apache2/sites-available/nextcloud.conf
    environment:
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
  db:
     image: mariadb:10.6
     container_name: db
     restart: unless-stopped
     command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
     volumes:
       - ./db:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=1234
       - MYSQL_PASSWORD=1234
       - MYSQL_DATABASE=nextcloud
       - MYSQL_USER=nextcloud
volumes:
  nextcloud-data: